name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/
        with:
          force-install: true

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
